### PR TITLE
Fix data races

### PR DESCRIPTION
**Pull request by glazychev-art**
#195

We cannot call `require(...)` inside other `require(...)`, because inner one call `t.FailNow()` in case of an error.

Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>

### CODE REVIEW

**Review by Mixaster995 — APPROVED** [review]

**Comment by d-uzlov** [comment]
How does this affect our tests?
This simple test doesn't show any issues with nested require calls:
```golang
func TestName(t *testing.T) {
	require.Eventually(t, func() bool {
		require.NotNil(t, nil)
		return true
	}, time.Second, time.Millisecond)
}
```
Are there some not obvious bugs caused by something in the tests, that get triggered by `t.FailNow`? How is nested require different from not-nested require here?

**Comment by glazychev-art** [comment]
@d-uzlov 
If you run `func TestName(t *testing.T) {...}` with `-race` flag you can see data races warning
```
==================
WARNING: DATA RACE
Write at 0x00c000001ea1 by goroutine 7:
  testing.(*common).FailNow()
      /usr/local/go/src/testing/testing.go:741 +0x4f
  testing.(*T).FailNow()
      <autogenerated>:1 +0x44
  github.com/stretchr/testify/require.Eventually()
      /home/art/go/pkg/mod/github.com/stretchr/testify@v1.7.0/require/require.go:334 +0x112
  github.com/networkservicemesh/sdk-sriov/pkg/networkservice/common/mechanisms/vfio_test.TestName()
      /home/art/go/src/github.com/networkservicemesh/sdk-sriov/pkg/networkservice/common/mechanisms/vfio/server_test.go:236 +0xc6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1194 +0x202

Previous write at 0x00c000001ea1 by goroutine 9:
  testing.(*common).FailNow()
      /usr/local/go/src/testing/testing.go:741 +0x4f
  testing.(*T).FailNow()
      <autogenerated>:1 +0x44
  github.com/stretchr/testify/require.NotNil()
  ...
```

**Comment by denis-tingaikin** [comment]
@d-uzlov as @glazychev-art noted `eventually` produces goroutines https://github.com/stretchr/testify/blob/master/assert/assertions.go#L1689

**Comment by d-uzlov** [comment]
Oh, yeah, makes sense.
I guess we should revise our other tests as well.

**Review by d-uzlov — APPROVED** [review]

**Review by Mixaster995 — APPROVED** [review]

**Review by denis-tingaikin — APPROVED** [review]

**Pull request merged**
