### PR TITLE
Update from update/networkservicemesh/sdk-kernel

### PR DESCRIPTION
**Pull request by nsmbot**
Update go.mod and go.sum to latest version from networkservicemesh/sdk-kernel@main
PR link: https://github.com/networkservicemesh/sdk-kernel/pull/307
Commit: eba0791
Author: Denis Tingaikin
Date: 2021-08-29 23:55:39 +0300
Message:
  - Merge pull request # 307 from Nordix/metadata-vfconfig

### CODE REVIEW

**Comment by denis-tingaikin** [comment]
@pperiyasamy Could you have a look?

**Comment by pperiyasamy** [comment]
@denis-tingaikin this gets addressed with PR https://github.com/networkservicemesh/sdk-sriov/pull/223. can we just close this PR ?

**Comment by denis-tingaikin** [comment]
@pperiyasamy yes, it makes sense :) 
I've pinged @Bolodya1997 to look at https://github.com/networkservicemesh/sdk-sriov/pull/223

**Comment by denis-tingaikin** [comment]
Closing by https://github.com/networkservicemesh/sdk-sriov/pull/223

**Pull request closed without merging**
