### PR TITLE
add vfconfig client chain element

### PR DESCRIPTION
**Pull request by pperiyasamy**
this enables facility to store vfinfo (pf, vf interface names, vf num) in resource pool client chain element and this info would get referred in further chain elements.

Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

### CODE REVIEW

**Comment by Bolodya1997** [comment]
`vfconfig` server injects VF config into the Request context, so it is accessible both from the server and from the client chain elements. If you want to create different VF configs for the server chain before `connect` and for the client chain in the `connect`, you probably need to add some `isClient` flag as it is done in `metadata`:
https://github.com/networkservicemesh/sdk/blob/fe8d8e6e825a3ff8024b8f8726eb028e2385ca1f/pkg/networkservice/utils/metadata/context.go#L49
In such case there is no need to add `vfconfig` client, you more probably just need to alter `vfconfig` context methods in the `sdk-kernel`:
https://github.com/networkservicemesh/sdk-kernel/blob/main/pkg/kernel/networkservice/vfconfig/context.go

So for me this client looks applicable only for the pure client chains (only on NSC), so if you are not planning to use it in there, I don't think that we need these changes.

**Comment by pperiyasamy** [comment]
@Bolodya1997 yes, you are correct, both client and server going to consume different `vfconfig`, so [this](https://github.com/networkservicemesh/sdk-kernel/blob/main/pkg/kernel/networkservice/vfconfig/context.go) must be enhanced to have isClient flag to have both server and client vfconfig. I think you meant to change `vfconfig/context.go `with APIs to something similar to [this](https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/tools/link/metadata.go).

**Comment by pperiyasamy** [comment]
This need rebase after this sdk-kernel [PR](https://github.com/networkservicemesh/sdk-kernel/pull/307) is merged and CI is expected to pass.

**Comment by denis-tingaikin** [comment]
@pperiyasamy Could you rebase this PR?

**Review by denis-tingaikin — APPROVED** [review]

**Comment by denis-tingaikin** [comment]
@Bolodya1997 Could you also review this?

**Review by Bolodya1997 — APPROVED** [review]

**Pull request merged**
